/* Database schema to keep the structure of entire database. */

/* FEATURE BRANCH 04-Add-join-table-for-visits */

-- A) Create a table named VETS with the following columns...
CREATE TABLE IF NOT EXISTS public.vets
(
    id integer NOT NULL DEFAULT nextval('vets_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    age integer,
    date_of_graduation date,
    CONSTRAINT vets_pkey PRIMARY KEY (id)
);

-- B) Add MANY-TO-MANY relationships with SPECIES & ANIMALS tables...

-- B-1) Creating the SPECIALIZATIONS join table:
CREATE TABLE IF NOT EXISTS public.specializations
(
    id integer NOT NULL DEFAULT nextval('specializations_id_seq'::regclass),
    vet_id integer NOT NULL,
    species_id integer NOT NULL,
    CONSTRAINT specializations_pkey PRIMARY KEY (id),
    CONSTRAINT fk_species_id FOREIGN KEY (species_id)
        REFERENCES public.species (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID,
    CONSTRAINT fk_vet_id FOREIGN KEY (vet_id)
        REFERENCES public.vets (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- B-2) Creating the VISITS join table:
CREATE TABLE IF NOT EXISTS public.visits
(
    id integer NOT NULL DEFAULT nextval('visits_id_seq'::regclass),
    animal_id integer NOT NULL,
    vet_id integer NOT NULL,
    date_of_visit date NOT NULL,
    CONSTRAINT visits_pkey PRIMARY KEY (id),
    CONSTRAINT fk_animal_id FOREIGN KEY (animal_id)
        REFERENCES public.animals (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_vet_id FOREIGN KEY (vet_id)
        REFERENCES public.vets (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);


/* FEATURE BRANCH 03-querying-multiple-tables */

-- A) Create new table called OWNERS with columns id, full_name & age.
CREATE TABLE owners
(
    id serial NOT NULL,
    full_name character varying(120) NOT NULL,
    age integer,
    PRIMARY KEY(id)
);

-- B) Create new table called SPECIES with columns id & name.
CREATE TABLE species
(
    id serial NOT NULL,
    name character varying(100) NOT NULL,
    PRIMARY KEY(id)
);

-- C) MODIFY animals table, make sure the id column is an autoincremented
--    PRIMARY KEY; remove column species; add column species_id (foreign key);
--     add column owner_id (foreign key).
ALTER TABLE animals
DROP COLUMN species,
ADD owner_id integer,
ADD species_id integer;

ALTER TABLE animals ADD PRIMARY KEY (id);

ALTER TABLE animals
    ADD CONSTRAINT fk_owner 
    FOREIGN KEY (owner_id) 
    REFERENCES owners (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    ADD CONSTRAINT fk_species
    FOREIGN KEY (species_id)
    REFERENCES species (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


/* FEATURE BRANCH 02-query-and-update-animals-table */

-- A) ADD a column species of type string to the animals table.
ALTER TABLE animals ADD species character varying(50);


/* FEATURE BRANCH 01-create-animals-table */

CREATE TABLE animals
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weight_kg real
);
